/**
 * All 85 official neighborhoods (bairros) of Porto Alegre, RS, Brazil.
 * Source: Lei Complementar Municipal nº 434/1999 and subsequent updates.
 */

export const PORTO_ALEGRE_NEIGHBORHOODS: string[] = [
  "Aberta dos Morros",
  "Agronomia",
  "Alto Petrópolis",
  "Anchieta",
  "Aparício Borges",
  "Arquipélago",
  "Azenha",
  "Bela Vista",
  "Belém Novo",
  "Belém Velho",
  "Boa Vista",
  "Bom Fim",
  "Bom Jesus",
  "Bonfim",
  "Camaquã",
  "Campo Novo",
  "Cascata",
  "Cavalhada",
  "Centro",
  "Centro Histórico",
  "Chapéu do Sol",
  "Chácara das Pedras",
  "Cidade Baixa",
  "Cristal",
  "Cristo Redentor",
  "Demolidor",
  "Estaleiro",
  "Espírito Santo",
  "Farrapos",
  "Farroupilha",
  "Floresta",
  "Glória",
  "Guarujá",
  "Higienópolis",
  "Hípica",
  "Humaitá",
  "Ilhas",
  "Ipanema",
  "Jardim Botânico",
  "Jardim Carvalho",
  "Jardim do Salso",
  "Jardim Floresta",
  "Jardim Itu",
  "Jardim Leopoldina",
  "Jardim Lindóia",
  "Jardim São Pedro",
  "Jardim Vila Nova",
  "Lami",
  "Lomba do Pinheiro",
  "Mário Quintana",
  "Mato Sampaio",
  "Medianeira",
  "Menino Deus",
  "Moinhos de Vento",
  "Mont'Serrat",
  "Navegantes",
  "Nonoai",
  "Nossa Senhora das Graças",
  "Passo das Pedras",
  "Passo do Estrela",
  "Petrópolis",
  "Pitinga",
  "Pompéia",
  "Ponta Grossa",
  "Praia de Belas",
  "Restinga",
  "Rio Branco",
  "Rubem Berta",
  "Santa Cecília",
  "Santa Maria Goretti",
  "Santa Rosa de Lima",
  "Santa Tereza",
  "Santana",
  "Santo Antônio",
  "São Geraldo",
  "São João",
  "São José",
  "São Sebastião",
  "Sarandi",
  "Serraria",
  "Teresópolis",
  "Três Figueiras",
  "Tristeza",
  "Uruguai",
  "Vila Assunção",
  "Vila Conceição",
  "Vila Ipiranga",
  "Vila João Pessoa",
].sort();
